import type { Gender } from '~/utils/gender'

// Transparent character cutouts generated by scripts/generateSealCutouts.py, shared by
// MayaPortrait.vue, MayaPortraitFrame.vue (hero), and MayaBust.vue (KINの関係性 relation cards).
// Male variants are suffixed `-male` (female is the default, unsuffixed set) — see that
// script's header comment.
const cutoutModules = import.meta.glob('~/assets/images/optimized/seal-*-cutout*.webp', { eager: true, import: 'default' }) as Record<string, string>
const CUTOUT_BY_INDEX: string[] = []
const CUTOUT_BY_INDEX_MALE: string[] = []
for (const [path, url] of Object.entries(cutoutModules)) {
  const maleMatch = path.match(/seal-(\d+)-cutout-male\.webp$/)
  if (maleMatch) {
    CUTOUT_BY_INDEX_MALE[Number(maleMatch[1])] = url
    continue
  }
  const match = path.match(/seal-(\d+)-cutout\.webp$/)
  if (match) CUTOUT_BY_INDEX[Number(match[1])] = url
}

const bustModules = import.meta.glob('~/assets/images/optimized/seal-*-bust*.webp', { eager: true, import: 'default' }) as Record<string, string>
const BUST_BY_INDEX: string[] = []
const BUST_BY_INDEX_MALE: string[] = []
for (const [path, url] of Object.entries(bustModules)) {
  const maleMatch = path.match(/seal-(\d+)-bust-male\.webp$/)
  if (maleMatch) {
    BUST_BY_INDEX_MALE[Number(maleMatch[1])] = url
    continue
  }
  const match = path.match(/seal-(\d+)-bust\.webp$/)
  if (match) BUST_BY_INDEX[Number(match[1])] = url
}

export function useSealCutouts() {
  return {
    // gender defaults to 'female' — falls back to the female asset if a male one is somehow
    // missing for a given index, so a partial asset set never renders a broken image.
    cutoutSrc: (sealIndex: number, gender: Gender = 'female') =>
      (gender === 'male' ? CUTOUT_BY_INDEX_MALE[sealIndex] : undefined) ?? CUTOUT_BY_INDEX[sealIndex],
    bustSrc: (sealIndex: number, gender: Gender = 'female') =>
      (gender === 'male' ? BUST_BY_INDEX_MALE[sealIndex] : undefined) ?? BUST_BY_INDEX[sealIndex]
  }
}
