// Transparent character cutouts generated by scripts/generateSealCutouts.py, shared by
// MayaPortrait.vue, MayaPortraitFrame.vue (hero), and MayaBust.vue (KINの関係性 relation cards).
const cutoutModules = import.meta.glob('~/assets/images/optimized/seal-*-cutout.webp', { eager: true, import: 'default' }) as Record<string, string>
const CUTOUT_BY_INDEX: string[] = []
for (const [path, url] of Object.entries(cutoutModules)) {
  const match = path.match(/seal-(\d+)-cutout\.webp$/)
  if (match) CUTOUT_BY_INDEX[Number(match[1])] = url
}

const bustModules = import.meta.glob('~/assets/images/optimized/seal-*-bust.webp', { eager: true, import: 'default' }) as Record<string, string>
const BUST_BY_INDEX: string[] = []
for (const [path, url] of Object.entries(bustModules)) {
  const match = path.match(/seal-(\d+)-bust\.webp$/)
  if (match) BUST_BY_INDEX[Number(match[1])] = url
}

export function useSealCutouts() {
  return {
    cutoutSrc: (sealIndex: number) => CUTOUT_BY_INDEX[sealIndex],
    bustSrc: (sealIndex: number) => BUST_BY_INDEX[sealIndex]
  }
}
